# Generated by Django 3.0.7 on 2020-08-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResourceList', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('url', models.CharField(max_length=50)),
                ('images', models.FileField(upload_to='uploads/')),
            ],
            options={
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='FrameWorks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('url', models.CharField(max_length=50)),
                ('images', models.FileField(upload_to='uploads/')),
            ],
            options={
                'verbose_name_plural': 'Framesworks',
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('url', models.CharField(max_length=50)),
                ('images', models.FileField(upload_to='uploads/')),
            ],
            options={
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('url', models.CharField(max_length=50)),
                ('images', models.FileField(upload_to='uploads/')),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='WebDevelopment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('url', models.CharField(max_length=50)),
                ('images', models.FileField(upload_to='uploads/')),
            ],
            options={
                'verbose_name_plural': 'Web Development',
            },
        ),
        migrations.AlterModelOptions(
            name='websites',
            options={'verbose_name_plural': 'Websites'},
        ),
    ]
